services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS: ${DB_PASS:-local_pass}


  # adapted from the postgres docker image docs: https://github.com/docker-library/docs/blob/master/postgres/README.md
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./src/config/init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-local_pass}